config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/openaire/iis:
      branch: master
      repo: https://github.com/openaire/iis.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/openaire/iis git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-orange-mandrill.sh
        container: qc.acc_breezy-razzmatazz-whippet
  QC.Doc:
    repos:
      github.com/openaire/iis find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-salmon-eagle.sh
        container: qc.doc_hazy-seashell-retriever
      github.com/openaire/iis git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-orchid-hare.sh
        container: qc.doc_craggy-olive-whippet
      github.com/openaire/iis markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-seashell-lynx.sh
        container: qc.doc_fuzzy-violet-dolphin
  QC.Lic:
    repos:
      github.com/openaire/iis licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-eggplant-zorse.sh
        container: qc.lic_smelly-bronze-cassowary
  QC.Sec:
    repos:
      github.com/openaire/iis bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-turquoise-bulldog.sh
        container: qc.sec_scaly-red-koala
  QC.Sty:
    repos:
      github.com/openaire/iis checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-silver-monster.sh
        container: qc.sty_slimy-lavender-starfish
      github.com/openaire/iis flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-salmon-havanese.sh
        container: qc.sty_hazy-sepia-frigatebird
      github.com/openaire/iis jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-maroon-dormouse.sh
        container: qc.sty_muzzy-flax-albatross
  QC.Uni:
    repos:
      github.com/openaire/iis pytest:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-smalt-gharial.sh
        container: qc.uni_nippy-ivory-coyote
  QC.Ver:
    repos:
      github.com/openaire/iis get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-malachite-zorse.sh
        container: qc.ver_greasy-turquoise-mongrel
timeout: 5400
